language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
install:
- npm install hexo-cli -g
- npm install
- git clone https://github.com/yangg/hexo-theme-even.git themes/even
addons:
  ssh_known_hosts: uedsky.com:1223
script:
- hexo generate
- rsync -az -vv --delete -e 'ssh -p 1223' public/ brook@uedsky.com:/var/www/blog
before_install:
- openssl aes-256-cbc -K $encrypted_6094e4f462c1_key -iv $encrypted_6094e4f462c1_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
